export const ActivityType = {
    USER_REGISTERED: "USER_REGISTERED",
    VENDOR_REGISTERED: "VENDOR_REGISTERED",
    VERIFICATION_REQUESTED: "VERIFICATION_REQUESTED",
    VENDOR_VERIFIED: "VENDOR_VERIFIED",
    SERVICE_FEATURED: "SERVICE_FEATURED",
    VENDOR_FEATURED: "VENDOR_FEATURED",
}